spring.datasource.username=agenda_app
spring.datasource.password=ViernesBuffet2026
app.admin.email=viernes@email.com
app.admin.senha=123456
app.restrito.email= funcionario@email.com
app.restrito.senha=123456