server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.forward-headers-strategy=framework
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never